/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import game.Jogo;
import game.Palavra;
import game.Users;
import javax.swing.JOptionPane;
import static telas.PrincipalTela.users;

/**
 *
 * @author leobe
 */
public class JogoTela extends javax.swing.JFrame {

    /**
     * Creates new form JogoTela
     */
    private Jogo jogo;

    public JogoTela() {
        initComponents();
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    
    // Metodos
    public void alteraLblDica(String dica) {
        lblDica.setText(dica);
    }
    
    public void alteraLblProgresso(String progresso) {
        lblProgresso.setText(progresso);
    }
    
    public void alteraLblPersonagem(String path) {
        lblPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }
    
    public void atualizaPont(String username, String dificuldade) {
        users.acrescentaPontuacao(username, dificuldade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPersonagem = new javax.swing.JLabel();
        pnlChutes = new javax.swing.JPanel();
        lblLetraIdent = new javax.swing.JLabel();
        lblPalavraIdent = new javax.swing.JLabel();
        txtLetraEntrada = new javax.swing.JTextField();
        txtPalavraEntrada = new javax.swing.JTextField();
        bttChuteLetra = new javax.swing.JButton();
        bttChutePalavra = new javax.swing.JButton();
        lblProgresso = new javax.swing.JLabel();
        lblDica = new javax.swing.JLabel();
        bttDesistir = new javax.swing.JButton();
        bttDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/playImage32.png")).getImage());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitle.setText("OnHangLine");

        lblPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HangMan1-removebg-preview.png"))); // NOI18N

        pnlChutes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Realize o Chute", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        lblLetraIdent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLetraIdent.setText("Chute Letra:");
        lblLetraIdent.setToolTipText("");

        lblPalavraIdent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPalavraIdent.setText("Chute Palavra");
        lblPalavraIdent.setToolTipText("");

        txtLetraEntrada.setToolTipText("Chute uma letra possível no campo ao lado.");

        txtPalavraEntrada.setToolTipText("Chute uma palavra possível no campo ao lado.");
        txtPalavraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalavraEntradaActionPerformed(evt);
            }
        });

        bttChuteLetra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/letraImage32.png"))); // NOI18N
        bttChuteLetra.setText("Confirmar Letra");
        bttChuteLetra.setToolTipText("Enviar letra para ser verificada");
        bttChuteLetra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttChuteLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttChuteLetraActionPerformed(evt);
            }
        });

        bttChutePalavra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/palavraImage32.png"))); // NOI18N
        bttChutePalavra.setText("Confirmar Palavra");
        bttChutePalavra.setToolTipText("Enviar palavra para ser verificada");
        bttChutePalavra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttChutePalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttChutePalavraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChutesLayout = new javax.swing.GroupLayout(pnlChutes);
        pnlChutes.setLayout(pnlChutesLayout);
        pnlChutesLayout.setHorizontalGroup(
            pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChutesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPalavraIdent)
                    .addComponent(lblLetraIdent))
                .addGap(18, 18, 18)
                .addGroup(pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLetraEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(txtPalavraEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttChuteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        pnlChutesLayout.setVerticalGroup(
            pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChutesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLetraIdent)
                    .addComponent(txtLetraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttChuteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnlChutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPalavraIdent)
                    .addComponent(txtPalavraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        lblProgresso.setFont(new java.awt.Font("Segoe UI", 0, 84)); // NOI18N
        lblProgresso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgresso.setToolTipText("");

        lblDica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bttDesistir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DesistirImage32.png"))); // NOI18N
        bttDesistir.setText("Desistir");
        bttDesistir.setToolTipText("Desistir deste Jogo.");
        bttDesistir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttDesistir.setBorderPainted(false);
        bttDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDesistirActionPerformed(evt);
            }
        });

        bttDica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bttDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dicaImage32.png"))); // NOI18N
        bttDica.setText("Dica");
        bttDica.setToolTipText("Clique aqui para receber uma ajuda.");
        bttDica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bttDesistir)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDica, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(165, 165, 165)
                        .addComponent(bttDica)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bttDesistir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(lblPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle)
                            .addComponent(bttDica))
                        .addGap(44, 44, 44)
                        .addComponent(lblDica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPalavraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalavraEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalavraEntradaActionPerformed

    private void bttChuteLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttChuteLetraActionPerformed
        // TODO add your handling code here:
        String tempLetraString = txtLetraEntrada.getText();
        if (tempLetraString.length() > 1) {
            JOptionPane.showMessageDialog(null, "Aceitamos somente uma letra neste campo.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (tempLetraString.length() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor não deixe o campo vazio.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.jogo.chutarLetra(tempLetraString.charAt(0));
            }
        }

        // Limpar Campos txt
       txtLetraEntrada.setText("");
        
    }//GEN-LAST:event_bttChuteLetraActionPerformed

    private void bttChutePalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttChutePalavraActionPerformed
        // TODO add your handling code here:
        String tempPalavra = txtPalavraEntrada.getText();
        if (tempPalavra.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor não deixe o campo vazio.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            this.jogo.chutarPalavra(tempPalavra);
        }
        
        // Limpar Campos txt
       txtPalavraEntrada.setText("");
    }//GEN-LAST:event_bttChutePalavraActionPerformed

    private void bttDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDicaActionPerformed
        // TODO add your handling code here:
        this.jogo.dica();
    }//GEN-LAST:event_bttDicaActionPerformed

    private void bttDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDesistirActionPerformed
        // TODO add your handling code here:
        this.jogo.desistir();
    }//GEN-LAST:event_bttDesistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttChuteLetra;
    private javax.swing.JButton bttChutePalavra;
    private javax.swing.JButton bttDesistir;
    private javax.swing.JButton bttDica;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblLetraIdent;
    private javax.swing.JLabel lblPalavraIdent;
    private javax.swing.JLabel lblPersonagem;
    private javax.swing.JLabel lblProgresso;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlChutes;
    private javax.swing.JTextField txtLetraEntrada;
    private javax.swing.JTextField txtPalavraEntrada;
    // End of variables declaration//GEN-END:variables
}
