/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import game.Palavra;
import game.Users;
import static java.awt.GridBagConstraints.BOTH;
import java.io.IOException;

/**
 *
 * @author leobe
 */
public class PrincipalTela extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    
    public PrincipalTela() {
        initComponents();   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameIcon = new javax.swing.JLabel();
        lblGameTitle = new javax.swing.JLabel();
        bttPlay = new javax.swing.JButton();
        bttSignUp = new javax.swing.JButton();
        bttSeeRank = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnHangLine");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/forcaImage32.png")).getImage());

        lblGameIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forcaImage256.png"))); // NOI18N
        lblGameIcon.setName("lblGameIcon"); // NOI18N

        lblGameTitle.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        lblGameTitle.setText("OnHangLine");

        bttPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/playImage32.png"))); // NOI18N
        bttPlay.setText("Start");
        bttPlay.setToolTipText("Jogar Forca");
        bttPlay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPlayActionPerformed(evt);
            }
        });

        bttSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userImage32.png"))); // NOI18N
        bttSignUp.setText(" SignUp and SignIn");
        bttSignUp.setToolTipText("Realizar Cadastro");
        bttSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSignUpActionPerformed(evt);
            }
        });

        bttSeeRank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rankImage32.png"))); // NOI18N
        bttSeeRank.setText("Check Ranking");
        bttSeeRank.setToolTipText("Visualizar Ranking");
        bttSeeRank.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttSeeRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSeeRankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblGameIcon)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblGameTitle)
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(bttSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttPlay)
                        .addGap(85, 85, 85)
                        .addComponent(bttSeeRank)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblGameIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblGameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttSignUp)
                            .addComponent(bttPlay)
                            .addComponent(bttSeeRank))))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSignUpActionPerformed
        // TODO add your handling code here:
        new UsersTela().setVisible(true);
    }//GEN-LAST:event_bttSignUpActionPerformed

    private void bttSeeRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSeeRankActionPerformed
        // TODO add your handling code here:
        new RankingTela().setVisible(true);
    }//GEN-LAST:event_bttSeeRankActionPerformed

    private void bttPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPlayActionPerformed
        // TODO add your handling code here:
        new JogoTela().setVisible(true);
    }//GEN-LAST:event_bttPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalTela().setVisible(true);
            }
        });
        
        Palavra palavras = new Palavra("./src/arquivos/Animais.txt", "./src/arquivos/DicasAnimais.txt", "./src/arquivos/DificuldadeAnimais.txt");
        Users users = new Users();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttPlay;
    private javax.swing.JButton bttSeeRank;
    private javax.swing.JButton bttSignUp;
    private javax.swing.JLabel lblGameIcon;
    private javax.swing.JLabel lblGameTitle;
    // End of variables declaration//GEN-END:variables
}
