/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import game.Palavra;
import game.Users;
import javax.swing.table.DefaultTableModel;
import static telas.PrincipalTela.users;

/**
 *
 * @author leobe
 */
public class RankingTela extends javax.swing.JFrame {
    
    /**
     * Creates new form Ranking
     */
    
    public RankingTela() {
        initComponents();
        this.carregarTabela();
    }
    
    public void carregarTabela() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Total Points", "Username"},0);
        for (int i = 0; i < users.getListaDeUsernames().size(); i++) {
            Object linha[] = new Object[]{users.getListaDePontosTotal().get(i), users.getListaDeUsernames().get(i)};
            modelo.addRow(linha);
        }
        
        // tabela recebe modelo
        tblTabelaUsers.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRankingUsers = new javax.swing.JPanel();
        scrRankingUsers = new javax.swing.JScrollPane();
        tblTabelaUsers = new javax.swing.JTable();
        bttSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ranking");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/rankImage32.png")).getImage());

        jpnRankingUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ranking do OnHangLine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblTabelaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Total Pontuation", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrRankingUsers.setViewportView(tblTabelaUsers);

        javax.swing.GroupLayout jpnRankingUsersLayout = new javax.swing.GroupLayout(jpnRankingUsers);
        jpnRankingUsers.setLayout(jpnRankingUsersLayout);
        jpnRankingUsersLayout.setHorizontalGroup(
            jpnRankingUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRankingUsersLayout.createSequentialGroup()
                .addComponent(scrRankingUsers)
                .addContainerGap())
        );
        jpnRankingUsersLayout.setVerticalGroup(
            jpnRankingUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRankingUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRankingUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        bttSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bttSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sairImage64.png"))); // NOI18N
        bttSair.setText("Sair");
        bttSair.setToolTipText("Sair do Ranking");
        bttSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRankingUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(bttSair)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRankingUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttSair)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bttSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSair;
    private javax.swing.JPanel jpnRankingUsers;
    private javax.swing.JScrollPane scrRankingUsers;
    private javax.swing.JTable tblTabelaUsers;
    // End of variables declaration//GEN-END:variables
}
